code updated with EC2 and user data
koraakdas/Terraformaws pull request #6
Opened 2022-06-11 18:53 UTC by koraakdas

Please check my code .

2022-06-12 13:13 UTC, vladimirmukhin requested changes

2022-06-12 13:13 UTC, vladimirmukhin commented on main.tf
> +    to_port     = 0
Please limit it to only ports that you are using, i.e. 22

2022-06-12 13:13 UTC, vladimirmukhin commented on main.tf
> +    cidr_blocks = ["0.0.0.0/0"]
Please have it as a variable and limit to the IP address of your ISP
```suggestion
    cidr_blocks = [var.client_public_ip]
```

2022-06-12 13:13 UTC, vladimirmukhin commented on main.tf
> +    Name = "${var.env_code}SecurityGrp"
Later you will have more than one security group
It will make sense to differentiate it
```suggestion
    Name = "${var.env_code}DefaultSecurityGrp"
```

2022-06-12 13:13 UTC, vladimirmukhin commented on main.tf
> +  count = 1
Count is not needed when we have a single resource
```suggestion
```

2022-06-12 13:13 UTC, vladimirmukhin commented on main.tf
> +  key_name                    = "terraformkey"
Could you please change the key name to `main`? It will allow me to troubleshoot the code more easily

2022-06-12 13:13 UTC, vladimirmukhin commented on main.tf
> +  ami                         = "ami-0f095f89ae15be883"
This will only work in a single region. You will have to change ami id if you want to deploy to other regions.
In order to avoid that, please  use this feature called data source:
https://www.terraform.io/language/state/remote-state-data

2022-06-12 13:13 UTC, vladimirmukhin commented on main.tf
> +}
Please add trailing newline

2022-06-12 19:49 UTC, koraakdas commented on main.tf
> +    cidr_blocks = ["0.0.0.0/0"]
cidr does not take a single IP i had to update the whole network of my isp

2022-06-15 20:26 UTC, vladimirmukhin commented on main.tf
> +    to_port     = 443
```suggestion
    from_port   = 80
    to_port     = 80
```

2022-06-17 13:09 UTC, vladimirmukhin approved these changes

2022-06-17 13:37 UTC, merged